export const textContent: { [key: string]: any } = {
  en: {
    landingTitle: "Digital Receptionist",
    greeting: "Hi, welcome to the digital receptionist!",
    startButton: "Start",
    form: {
      title: "Please enter your information below",
      firstName: "First name",
      lastName: "Last name",
      email: "Email",
      company: "Company",
      nextStep: "Next",
      validation: {
        minLength: "is too short",
        maxLength: "is too long",
        required: "is required",
        pattern: "is invalid",
      },
    },
    nextStepTitle: "Who did you book an appointment with?",
    notifyButton: "Notify",
    searchPlaceholder: "Start typing a name...",
    noBookedAppointment: "No booked appointment",
    alertTitle: "Notification sent!",
    alertBody: "<p>We will be with you shortly, please wait in the lobby.</p>",
    alertClosing:
      "<strong>This window will automatically close in <b></b></strong>",
  },
  sv: {
    landingTitle: "Digital Receptionist",
    greeting: "Hej, välkommen till den digitala receptionisten!",
    startButton: "Starta",
    form: {
      title: "Vänligen fyll i dina uppgifter nedan",
      firstName: "Förnamn",
      lastName: "Efternamn",
      email: "Epost",
      company: "Företag",
      nextStep: "Nästa",
      validation: {
        minLength: "är för kort",
        maxLength: "är för långt",
        required: "är obligatoriskt",
        pattern: "är ogiltlig",
      },
    },
    nextStepTitle: "Vem har du bokat tid med?",
    notifyButton: "Meddela",
    searchPlaceholder: "Börja skriva ett namn...",
    noBookedAppointment: "Ingen bokad tid",
    alertTitle: "Meddelande skickat!",
    alertBody: "Vi kommer snart och möter dig, vänligen vänta i lobbyn.<br />",
    alertClosing:
      "<strong>Detta fönster stängs automatiskt om <b></b></strong>",
  },
};
